name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t legalapp .

      - name: Run FastAPI application and test Q&A
        run: |
          docker run -p 8000:8000 legalapp
          sleep 10  # Wait for the server to start
          curl -X POST "http://localhost:8000/qa" -H "Content-Type: application/x-www-form-urlencoded" \
          -d "Question=What is the legal definition of negligence?&Context=Negligence is the failure to take proper care in doing something."
          docker stop $(docker ps -q)  # Stop the running container

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub (or another registry)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image
        run: |
          docker tag legalapp furkmak/legalapp:latest
          docker push furkmak/legalapp:latest
